image: Ubuntu

stack: jdk 1.8
branches:
  only:
    - master

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-order.jar &
  - chmod +x ./driver/linux/chromedriver

build_script:
  - ./gradlew test --info